name: Build, Test and Code Scanning

on:
  push:
    branches:
      - master

permissions:
  actions: read
  contents: read
  security-events: write
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.1
      with:
        submodules: true

    - name: Setup .NET
      uses: actions/setup-dotnet@v1.9.0
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore "motohutS3API_metTestproject/motohut_security/Motohut API.sln"

    - name: Build
      run: dotnet build "motohutS3API_metTestproject/motohut_security/Motohut API.sln" --no-restore

    - name: Test
      run: dotnet test motohutS3API_metTestproject/Motohut_Integratrietesten/ --no-build --verbosity normal

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: csharp
        
    - name: Autobuild
      uses: github/codeql-action/autobuild@v2

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
